blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogDeleteView, BlogUpdateView
from blog.apps import BlogConfig
# вызов функции при получении определенного запроса

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog'),
    path('create/', never_cache(BlogCreateView.as_view()), name='create'),
    path('update/<int:pk>/', never_cache(BlogUpdateView.as_view()), name='update'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


NULLABLE = {'null': True, 'blank': True}


class Blog(models.Model):
    """
    Модель блога
    """
    title = models.CharField(max_length=100, verbose_name='заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    context = models.TextField(verbose_name='описание')
    preview = models.ImageField(verbose_name='превью', **NULLABLE)
    create = models.DateField(verbose_name='дата создания', auto_now=True)
    is_publish = models.BooleanField(verbose_name='статус публикации', default=True)
    count_views = models.IntegerField(verbose_name='счётчик просмотров', default=0)

    def __str__(self):
        return (f"{self.title} {self.slug} {self.context} {self.preview} {self.create} \
{self.is_publish} {self.count_views}")

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

blog/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render
from blog.models import Blog
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django.core.mail import send_mail
from django.urls import reverse_lazy
from pytils.translit import slugify


# Create your views here.


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'context', 'preview')
    success_url = reverse_lazy('blog:blog')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_views += 1
        self.object.save()
        if self.object.count_views == 100:
            subject = 'Условие выполнено'
            message = 'Условие было выполнено.'
            from_email = 'EMAIL'
            recipient_list = ['EMAIL']  # Укажите адрес получателя
            send_mail(subject, message, from_email, recipient_list)
        return self.object


class BlogUpdateView(PermissionRequiredMixin, UpdateView):
    model = Blog
    fields = ('title', 'context', 'preview')
    permission_required = 'blog.change_post'

    def get_success_url(self):
        return reverse_lazy('blog:view', kwargs={'pk': self.object.pk})


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html'%}
{% block content %}
<div class="container">
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Удалить материал?</p>
                        <button type="submit" class="btn btn-outline-dark">Да</button>
                        <a href="{% url 'blog:blog' %}" type="button" class="btn btn-outline-dark">Отменить</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html'%}
{% block content %}
{% load my_tags %}

<div class="container">
    <div class="row text-center">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <h3 class="card-title pricing-card-title ">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <img src="{% mediapath object.preview %}" width="100" height="300" class="card-img-top">
                        <li>- {{ object.context }}</li>
                        <li>- Дата создания: {{object.create}}</li>
                        <li>- Количество просмотров: {{object.count_views}}</li>
                    </ul>
                </div>

            </div>
        </div>
    </div>

    <!-- Button trigger modal -->
    <div class="m-3">
        <a href="{% url 'blog:blog' %}" class="btn btn-outline-dark">Назад</a>
    </div>


    {% endblock %}
</div>

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html'%}
{% block content %}
<div class="container">
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn-outline-dark">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html'%}
{% load my_tags %}
{% block content %}

<div class="container">
    <div class="row text-center">
    <a href="{% url 'blog:create'%}" type="button" class="btn mb-3 btn-outline-secondary">Создать новость</a>
    {% for object in object_list %}
        {% if object.is_publish %}
<div class="col-6">
    <div class="card shadow-sm mb-3">
        <h3>{{object.title}}</h3>
        <img src="{% mediapath object.preview %}" width="100" height="300" class="card-img-top">
        <div class="card-body">
            <p class="card-text">{{object.context|truncatechars:100}}</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'blog:view' object.pk %}" type="button" class="btn btn-outline-dark">Посмотреть</a>
                    <a href="{% url 'blog:delete_blog' object.pk %}" type="button" class="btn btn-outline-dark">Удалить</a>
                    <a href="{% url 'blog:update' object.pk %}" type="button" class="btn btn-outline-dark">Изменить</a>
                </div>
                <small class="text-body-secondary">Дата создания: {{object.create}} </small>
            </div>
        </div>
    </div>
</div>
        {% else %}
        {% endif %}
{% endfor %}
</div>
</div>
{% endblock %}