blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogDeleteView, BlogUpdateView
from blog.apps import BlogConfig
# вызов функции при получении определенного запроса

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog'),
    path('create/', never_cache(BlogCreateView.as_view()), name='create'),
    path('update/<int:pk>/', never_cache(BlogUpdateView.as_view()), name='update'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog'),

]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.views import ContactListView, ProductDetailView, ProductListView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView
from catalog.apps import CatalogConfig

# вызов функции при получении определенного запроса

app_name = CatalogConfig.name

urlpatterns = [
    path('contacts/', ContactListView.as_view(), name='contact'),
    path('', ProductListView.as_view(), name='home'),
    path('product/<int:pk>/', cache_page(180)(ProductDetailView.as_view()), name='product_details'),
    path('create_product/', never_cache(ProductCreateView.as_view()), name='create_product'),
    path('update_product/<int:pk>/', never_cache(ProductUpdateView.as_view()), name='update_product'),
    path('delete_product/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, verification, forgotten_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('verification/', verification),
    path('forgotten_password/', forgotten_password, name='forgotten_password'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from users.services import random_key

NULLABLE = {'null': True, 'blank': True}


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='почта')

    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    phone = models.CharField(max_length=40, verbose_name='телефон', **NULLABLE)
    country = models.CharField(max_length=100, verbose_name='страна', **NULLABLE)
    mail_key = models.CharField(max_length=30, default=random_key(),  verbose_name='ключ')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfiledForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget = forms.EmailInput(attrs={'readonly': 'readonly'})
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from users.forms import UserRegisterForm, UserProfiledForm
from users.models import User
from users.services import _send_mail, random_key, create_password


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        if form.is_valid():
            new_user = form.save()
            key = random_key()
            new_user.mail_key = key
            new_user.is_active = False
            new_user.save()
            _send_mail('Верификация', f'http://127.0.0.1:8000/users/verification/?key={key}', new_user.email)

        return super().form_valid(form)


def verification(request):
    key = request.GET.get('key')
    users = User.objects.filter(mail_key=key)[0]
    if users:
        users.is_active = True
        users.save()
    return redirect('catalog:home')


def forgotten_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        user = User.objects.filter(email=email)[0]
        if user:
            password = create_password()
            user.set_password(password)
            user.save()
            _send_mail('Новый пароль', f'Новый пароль: {password}', email)
            return redirect('catalog:home')

    return render(request, 'users/forgotten_password.html')


class ProfileView(UpdateView):
    model = User
    form_class = UserProfiledForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

users/templates/users/forgotten_password.html
{% extends 'catalog/base.html'%}
{% block content %}

<div class="container" align="center">
    <div class="col-12">
        <form method="post" class="row">
            <div class="col-4"></div>
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <div>
                            {% csrf_token %}
                            <label for="email">Почта</label>
                            <input type="email" name="email" class="form-control" id="email"
                                   placeholder="example@example.example">
                            <input type="submit" class="btn m-2 btn-block btn-outline-dark" value="Отправить">
                        </div>
                    </div>
                </div>

            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html'%}
{% block content %}
{% load crispy_forms_tags %}

<div class="container" align="center">
    <div class="col-12">
        <form method="post" class="row">
            <div class="col-4"></div>
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <div>
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="btn-group">
                                <button type="submit" class="btn btn-block btn-outline-dark">Войти</button>
                                <a href="{% url 'catalog:home' %}" class="btn btn-block btn-outline-dark">Назад</a>
                            </div>
                            <a href="{% url 'users:forgotten_password' %}" class="btn m-2 btn-block btn-outline-dark">Забыли
                                пароль?</a></div>
                    </div>
                </div>
            </div>

    </div>
    </form>
</div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html'%}
{% block content %}
{% load crispy_forms_tags %}

<div class="container" align="center">
<div class="col-12">
    <form method="post" class="row">
        <div class="col-4"></div>
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <div>
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="btn-group">
                            <button type="submit" class="btn btn-block btn-outline-dark">
                                Регистрация
                            </button>
                            <a href="{% url 'catalog:home' %}" class="btn btn-block btn-outline-dark">Назад</a></div>

                    </div>
                </div>
            </div>

        </div>
    </form>
</div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html'%}
{% block content %}
{% load crispy_forms_tags %}

<div class="container" align="center">
<div class="col-12">
    <form method="post" class="row">
        <div class="col-4"></div>
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <div>
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="btn-group">
                            <button type="submit" class="btn btn-block btn-outline-dark">
                                Сохранить
                            </button>
                            <a href="{% url 'catalog:home' %}" class="btn btn-block btn-outline-dark">Назад</a></div>

                    </div>
                </div>
            </div>

        </div>
    </form>
</div>
</div>
{% endblock %}