blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogDeleteView, BlogUpdateView
from blog.apps import BlogConfig
# вызов функции при получении определенного запроса

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog'),
    path('create/', never_cache(BlogCreateView.as_view()), name='create'),
    path('update/<int:pk>/', never_cache(BlogUpdateView.as_view()), name='update'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog'),

]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.views import ContactListView, ProductDetailView, ProductListView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView
from catalog.apps import CatalogConfig

# вызов функции при получении определенного запроса

app_name = CatalogConfig.name

urlpatterns = [
    path('contacts/', ContactListView.as_view(), name='contact'),
    path('', ProductListView.as_view(), name='home'),
    path('product/<int:pk>/', cache_page(180)(ProductDetailView.as_view()), name='product_details'),
    path('create_product/', never_cache(ProductCreateView.as_view()), name='create_product'),
    path('update_product/<int:pk>/', never_cache(ProductUpdateView.as_view()), name='update_product'),
    path('delete_product/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, verification, forgotten_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('verification/', verification),
    path('forgotten_password/', forgotten_password, name='forgotten_password'),

]

catalog/models.py
from django.db import models

from users.models import User

# Create your models here.

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    """
    Модель категории
    """
    name = models.CharField(max_length=50, verbose_name='название')
    description = models.TextField(verbose_name='описание')

    def __str__(self):
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    """
    Модель продуктов
    """
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='владелец', **NULLABLE)

    name = models.CharField(max_length=100, verbose_name='название')
    description = models.TextField(verbose_name='описание')
    preview = models.ImageField(verbose_name='превью', **NULLABLE)
    price = models.PositiveIntegerField(verbose_name='цена')
    create_date = models.DateField(verbose_name='дата создания', auto_now=True)
    date_of_change = models.DateField(verbose_name='дата изменения', auto_now_add=True)
    publish = models.BooleanField(default=False, verbose_name='публикация')

    def __str__(self):
        return (f'{self.name} {self.description} {self.preview} \
{self.category} {self.price} {self.create_date} {self.date_of_change}')

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')

    number_version = models.PositiveIntegerField(verbose_name='номер версии')
    title_version = models.CharField(max_length=150, verbose_name='название версии')
    current_version = models.BooleanField(verbose_name='признак текущий версии')

    def __str__(self):
        return f'{self.number_version} {self.title_version} {self.current_version}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'


class Contact(models.Model):
    """
    Модель контактов
    """
    country = models.CharField(max_length=50, verbose_name='страна')
    address = models.TextField(verbose_name='адрес')

    def __str__(self):
        return f'{self.country} {self.address}'

    class Meta:
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'

catalog/forms.py
from django import forms
from catalog.models import Product, Version


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'current_version':
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        fields = ('name', 'description', 'category', 'price',)

    def clean(self):
        cleaned_date = super().clean()
        name = cleaned_date['name']
        description = cleaned_date['description']
        if set(self.forbidden_words) & set(description.lower().split()) or set(self.forbidden_words) & set(
                name.lower().split()):
            raise forms.ValidationError('Используется запрещенное слово')

        return cleaned_date


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from catalog.forms import ProductForm, VersionForm
from catalog.models import Contact, Product, Version
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.forms import inlineformset_factory
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin

from catalog.services import get_cached_category


# Create your views here.


class ContactListView(ListView):
    """
    Контролер для вывода контактов
    """
    model = Contact
    template_name = 'catalog/contact.html'


class ProductDetailView(LoginRequiredMixin, DetailView):
    """
    Контролер для детальной информации продуктов
    """
    model = Product
    context_object_name = 'article'


class ProductListView(ListView):
    """
    Контролер для показа продуктов
    """
    model = Product
    template_name = 'catalog/home.html'


class ProductCreateView(LoginRequiredMixin, CreateView):
    """
    Контролер для добавления продуктов
    """
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')

    def form_valid(self, form):
        if form.is_valid():
            product = form.save()
            product.owner = self.request.user
            product.save()
        return super().form_valid(form)

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['category'] = get_cached_category()
        return context_data


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')
    permission_required = 'catalog.change_post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)
        context['formset'] = formset
        return context

    def test_func(self):
        return self.request.user == self.object.owner


    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product')

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Online-shop</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-i tems-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">Online-store</a>

    <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        {% if user.is_authenticated %}
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'users:profile' %}">Профиль</a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'users:login' %}">Войти</a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>


{% block content %}
{% endblock %}
<div class="container">
    <div class="row text-start">

        <footer class="pt-3 my-md-5 md-5 border-top">
            <div>
                <div class="row text-start">
                    <div class="col-12 col-md">
                        Online-store
                        <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Категории</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="#">Рассылки</a></li>
                            <li><a class="text-muted" href="#">Телеграм боты</a></li>
                            <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                            <li><a class="text-muted" href="#">Веб-приложения</a></li>
                            <li><a class="text-muted" href="#">Микросервисы</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Дополнительно</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="{% url 'blog:blog' %}">Мы пишем</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>О нас</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="{% url 'catalog:contact' %}">Контакты</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/contact.html
{% extends 'catalog/base.html'%}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Наши контакты</h1>
    <div class="container">
        <div class="row text-start">

            <div class="col-lg-9 col-md-6 col-sm-12">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Страна</th>
                        <th scope="col">Адрес</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in object_list %}
                    <tr>
                        <td>{{ object.country }}</td>
                        <td>{{ object.address }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                       required>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Телефон</label>
                                <input type="text" name="phone" class="form-control" id="phone"
                                       placeholder="Контактный телефон" required>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message"
                                          placeholder="Сообщение" required></textarea>
                            </div>
                            <input type="submit" class="btn btn-lg btn-block btn-outline-primary" value="Отправить"/>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html'%}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4 text-primary">Online-store</h1>
</div>
{% include 'catalog/includes/inc_home_product.html'%}
{% if user.is_authenticated %}
<div class="col-12">
    <p>
    <div class="text-center">
    <div class="btn-group">
        <a href="{% url 'catalog:create_product' %}" class="btn btn-block btn-outline-dark">Добавить продукт</a>
    <a href='#' class="btn btn-block btn-outline-dark">Добавить категорию</a>
    </div>
</div>
    </p>
    {% endif %}
</div>

{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html'%}
{% block content %}
<div class="container">
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Удалить продукт {{object.name}}?</p>
                        <div class="btn-group">
                        <button type="submit" class="btn-outline-dark">Да</button>
                        <a href="{% url 'catalog:home' %}" type="button" class="btn-outline-dark ">Отмена</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html'%}
{% block content %}

<div class="container">
    <div class="row text-center">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ article.name }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title ">Цена:
                        <p>$ {{article.price}}</p></h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ article.description }}</li>
                        <li>- Дата создания: {{ article.create_date}}</li>
                        <li>- Дата изменение: {{ article.date_of_change}}</li>
                    </ul>
                </div>

            </div>
        </div>
    </div>

    <!-- Button trigger modal -->
    <div class="btn-group">
        <a href="{% url 'catalog:delete_product' object.id %}" class="btn btn-outline-dark">Удалить продукт</a>
            <a href="{% url 'catalog:home' %}" class="btn btn-outline-dark">Назад</a>
    </div>

    {% endblock %}
</div>

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html'%}
{% block content %}
{% load crispy_forms_tags %}

<div class="container">
    <form method="post" class="row">
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <div>
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="btn-group">
                            <button type="submit" class="btn btn-outline-dark">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                            <a href="{% url 'catalog:home' %}" class="btn btn-outline-dark">Назад</a></div>

                    </div>
                </div>
            </div>
        </div>
        {% if object %}
        <div class="col-6">
            <div class="card mb-4 box-shadow   ">
                <div class="card-header">
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        {% endif %}
    </form>
</div>
{% endblock %}